### ISSUE TITLE
kit-client redefine architecture

### ISSUE THREAD

**Issue by Gruce** [EnabApp/EnabApp#4]
- [ ] kit-auth
- [ ] frontend-enab
- [ ] frontend-dashboard
- [ ] admin-dashboard

**Comment by Gruce** [comment]
Hello,

we have three challenges here in the new `kit-client`:
- [ ] Making robust sync with the backend api depends on OpenAPI https://github.com/EnabApp/kit-client/issues/2.
- [ ] Making our own client relying on Nitro Proxy instead of making individual api routes. https://github.com/EnabApp/kit-client/issues/3
- [ ] Dealing with data with our client. https://github.com/EnabApp/kit-client/issues/5


We should treat each challenge here as an individual issue.


@eq0 @HassanKadhim Any ideas?
